config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  get "chats/:id" => "chats#show", as: "chat"
  get "cate_search" => "homes#cate_search"
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
      get "follows" => "users#follows"
      get "followers" => "users#followers"
      get "book_search" => "users#book_search"
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :chats, only: [:create]
  resources :groups do
    get "join" => "groups#join"
  end
end

app/models/group.rb
class Group < ApplicationRecord
  attachment :image

  validates :name, presence: true
  validates :introduction, presence: true


  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to groups_path
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  private
    def group_params
      params.require(:group).permit(:name, :introduction, :image)
    end

    def ensure_correct_user
      @group = Group.find(params[:id])
      if @group.owner_id != current_user.id
        redirect_to groups_path
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group, local: true do |f| %>
  <div class="form-group">
    <%= f.label :グループ名 %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :introduction, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :グループ画像 %>
    <%= f.attachment_field :image, class:"form-control-file" %>
  </div>
  <%= f.submit class:"btn btn-info" %>
<% end %>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-11 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-3">
      <h2>Editing Group</h2>
      <%= render "groups/form", group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container mt-3">
  <%= render "books/error", model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: current_user %>
      <h2>New book</h2>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td>
                <%= attachment_image_tag group, :image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
              </td>
              <td><%= link_to group.name, group_path(group) %></td>
              <td><%= group.introduction %></td>
              <td><%= group.users.count %></td>
              <td>
                <% if group.owner_id == current_user.id %>
                  <%= link_to "Edit", edit_group_path(group), class:"btn btn-success btn-sm" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-11 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-3">
      <h2>Create Group</h2>
      <%= render "groups/form", group: @group %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container mt-3">
  <%= render "books/error", model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: current_user %>
      <h2>New book</h2>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Group Detail</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag @group, :image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
            </td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |user| %>
                <%= user.name %>
              <% end %>
            </td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to "Edit", edit_group_path(@group), class:"btn btn-success btn-sm" %>
              <% elsif @group.users.include?(current_user) %>
                <%= link_to "Leave this group", group_path(@group), method: :delete, class:"btn btn-danger btn-sm" %>
              <% else %>
                <%= link_to "Join this group", group_join_path(@group), class:"btn btn-success btn-sm" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>