config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  get "chats/:id" => "chats#show", as: "chat"
  get "cate_search" => "homes#cate_search"
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
      get "follows" => "users#follows"
      get "followers" => "users#followers"
      get "book_search" => "users#book_search"
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :chats, only: [:create]
  resources :groups do
    get "join" => "groups#join"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: {in: 2..20 }
  validates :introduction, length: {maximum: 50}
  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following
  has_many :user_rooms, dependent: :destroy
  has_many :chats
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.looks(word, search)
    if search == "perfect_match"
      User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      User.where("name LIKE?", "#{word}%")
    elsif search == "backword_match"
      User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      User.where("name LIKE?", "%#{word}%")
    else
      User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    @the_day_before = @today_book.count / @yesterday_book.count.to_f
    @the_week_before = @this_week_book.count / @last_week_book.count.to_f
    @six_days_ago_book = @books.where(created_at: 6.day.ago.all_day).count
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def follows
    @user = User.find(params[:user_id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:user_id])
    @users = @user.followers
  end

  def book_search
    @user = User.find(params[:user_id])
    @books = @user.books
    create_at = params[:created_at]
    if create_at == ""
      @book_search = "日付を入力してください"
    else
      @book_search = @books.where("created_at LIKE?", "#{create_at}%").count
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end

    def ensure_correct_user
      @user = User.find(params[:id])
      if @user != current_user
        redirect_to user_path(current_user)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_book_search.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= book_search %></td>
    </tr>
  </tbody>
</table>

app/views/users/_follow.html.erb
<% if users.present? %>
  <table class="table">
   <thead>
     <tr>
       <th>image</th>
       <th>name</th>
       <th colspan="3"></th>
     </tr>
   </thead>
   <tbody>
      <% users.each do |user| %>
        <tr>
         <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40"  %></td>
         <td><%= user.name %></td>
         <td>フォロー数:<%= user.active_relationships.count %></td>
         <td>フォロワー数:<%= user.passive_relationships.count %></td>
         <td><%= link_to "Show", user_path(user) %></td>
        </tr>
      <% end %>
   </tbody>
  </table>
<% else %>
  ユーザーはいません
<% end %>

app/views/users/_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, format: "jpeg", fallback:"no_image.jpg", size: "100x100" %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th><%= link_to user.active_relationships.count, user_follows_path(user) %></th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to user.passive_relationships.count, user_followers_path(user) %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <% if user == current_user %>
    <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% elsif user.followed_by?(current_user) %>
    <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class: "btn btn-info btn-sm" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-success btn-sm" %>
  <% end %>
  
  <% if user.followed_by?(current_user) && current_user.followed_by?(user) %>
    <%= link_to "chatを始める", chat_path(user) %>
  <% end %>
</div>

app/views/users/book_search.js.erb
$('#search_result').html("<%= j(render "users/book_search", book_search: @book_search) %>")

app/views/users/edit.html.erb
<div class="container">
  <%= render "books/error", model: @user %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-3">
      <h2>User info</h2>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :Name %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :Image %>
          <%= f.attachment_field :profile_image, class:"form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.label :Introduction %>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <%= f.submit "Update User", class:"btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<%= render "users/follow", users: @users %>

app/views/users/follows.html.erb
<h2>Follow Users</h2>
<%= render "users/follow", users: @users %>

app/views/users/index.html.erb
<div class="container mt-3">
  <%= render "books/error", model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: current_user %>
      <h2>New book</h2>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %> |
      <%= link_to "グループ一覧", groups_path %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
              </td>
              <td><%= user.name %></td>
              <td>フォロー数<%= user.active_relationships.count %></td>
              <td>フォロワー数<%= user.passive_relationships.count %></td>
              <td>
                <% if user != current_user %>
                  <% if user.followed_by?(current_user) %>
                    <%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(user), method: :post %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-3">
  <%= render "books/error", model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <h2>New book</h2>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @user.books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <h2>投稿数の前日比・前週比</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @today_book.count %></td>
            <td><%= @yesterday_book.count %></td>
            <td>
              <% if @yesterday_book.count == 0 %>
                前日の投稿数が0のため計算できません
              <% else %>
                <%= (@the_day_before * 100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>前週の投稿数</th>
            <th>前週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @this_week_book.count %></td>
            <td><%= @last_week_book.count %></td>
            <td>
              <% if @last_week_book.count == 0 %>
                前週の投稿数が0のため計算できません
              <% else %>
                <%= (@the_week_before * 100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

      <h2>7日間分の投稿数</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>6日前</th>
            <th>5日前</th>
            <th>4日前</th>
            <th>3日前</th>
            <th>2日前</th>
            <th>1日前</th>
            <th>今日</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @books.created_6days_ago.count %></td>
            <td><%= @books.created_5days_ago.count %></td>
            <td><%= @books.created_4days_ago.count %></td>
            <td><%= @books.created_3days_ago.count %></td>
            <td><%= @books.created_2days_ago.count %></td>
            <td><%= @yesterday_book.count %></td>
            <td><%= @today_book.count %></td>
          </tr>
        </tbody>
      </table>
      <%= form_with url: user_book_search_path(@user), method: :get do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit "検索", class: "btn btn-primary" %>
      <% end %>
      <h2>検索結果</h2>
      <div id="search_result">
        <% if @book_search.present? %>
          <%= render "users/book_search", book_search: @book_search %>
        <% end %>
      </div>
    </div>
  </div>
</div>